*&---------------------------------------------------------------------*
*&  Include           ZEDR13_HW002_SCR
*&---------------------------------------------------------------------*

TABLES : ZEDT13_100 , ZEDT13_101 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZORDNO .
  SELECT-OPTIONS : S_ZORDNO FOR ZEDT13_100-ZORDNO .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_ZID .
  PARAMETERS : P_ZID LIKE ZEDT13_100-ZIDCODE .
SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZMATNR .
  SELECT-OPTIONS : S_ZMATNR FOR ZEDT13_100-ZMATNR .
SELECTION-SCREEN END OF LINE.
" 주문일자와 관련된 COMMENT 및 SELECT-OPTIONS 함께 배치
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZJDATE MODIF ID M1.
  SELECT-OPTIONS : S_ZJDATE FOR ZEDT13_100-ZJDATE MODIF ID M1.
SELECTION-SCREEN END OF LINE.

" 배송일자와 관련된 COMMENT 및 SELECT-OPTIONS 함께 배치
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZDDATE MODIF ID M2.
  SELECT-OPTIONS : S_ZDDATE FOR ZEDT13_101-ZDDATE MODIF ID M2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_RORD RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_RDELV  RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .

" [SCREEN] 2. 반품내역포함엔 체크박스로 기본적으로 X표기 기표
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME .
PARAMETERS : Z_RETCH AS CHECKBOX DEFAULT 'X' .
SELECTION-SCREEN END OF BLOCK B3 .