*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_IR_SCR
*&---------------------------------------------------------------------*

TABLES : ZEDT13_208, ZEDT13_209 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
"---입고생성
"PO번호
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_EBELN1 MODIF ID M1 .
  PARAMETERS : P_EBELN1  LIKE ZEDT13_209-ZMSEG_EBELN MODIF ID M1 .
SELECTION-SCREEN END OF LINE .

"플랜트
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_WERKS1 MODIF ID M1 .
  PARAMETERS : P_WERKS1  LIKE ZEDT13_209-ZMSEG_WERKS  MODIF ID M1 .
SELECTION-SCREEN END OF LINE .

"송장처리일
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_DATS1 MODIF ID M1 .
  PARAMETERS : P_DATS1  LIKE ZEDT13_208-ZRBKP_BUDAT MODIF ID M1 .
SELECTION-SCREEN END OF LINE .

"---입고조회
  "구매오더
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_EBELN2 MODIF ID M2 .
  PARAMETERS : P_EBELN2  LIKE ZEDT13_209-ZMSEG_EBELN MODIF ID M2 .
SELECTION-SCREEN END OF LINE.
"플랜트
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_WERKS2 MODIF ID M2 .
  PARAMETERS : P_WERKS2  LIKE ZEDT13_209-ZMSEG_WERKS MODIF ID M2 .
SELECTION-SCREEN END OF LINE .

SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_CREATE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_LOOKUP RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .