*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_IR_TOP
*&---------------------------------------------------------------------*

DATA : OK_CODE TYPE SY-UCOMM .
DATA : GV_FOUND TYPE C LENGTH 1 .
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID .

DATA : GS_FIELDCAT TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT TYPE LVC_T_FCAT .

DATA : BEGIN OF GS_PURCHASE ,
  L_CHECK TYPE C LENGTH 1,
  ZEKKPO_EBELN TYPE ZEDT13_205-ZEKKPO_EBELN ,
  ZEKKO_BUKRS TYPE ZEDT13_204-ZEKKO_BUKRS ,
  ZEKPO_EBELP TYPE ZEDT13_205-ZEKPO_EBELP,
  ZEKKO_LIFNR TYPE ZEDT13_204-ZEKKO_LIFNR,
  ZEKKO_BEDAT TYPE ZEDT13_204-ZEKKO_BEDAT,
  ZEKPO_MATNR TYPE ZEDT13_205-ZEKPO_MATNR,
  ZMAKT_MAKTX TYPE ZEDT13_205-ZMAKT_MAKTX,
  ZEKPO_MENGE TYPE ZEDT13_205-ZEKPO_MENGE,
  ZEKPO_MEINS TYPE ZEDT13_205-ZEKPO_MEINS,
  ZEKPO_BPRME TYPE ZEDT13_205-ZEKPO_BPRME,
  ZEKKO_WAERS TYPE ZEDT13_204-ZEKKO_WAERS,
  ZEKPO_PRDAT TYPE ZEDT13_205-ZEKPO_PRDAT ,
  ZEKPO_WERKS TYPE ZEDT13_205-ZEKPO_WERKS,
  ZEKPO_LGORT TYPE ZEDT13_205-ZEKPO_LGORT,
  "거래금액
  ZBSIK_DMBTR TYPE ZEDT13_209-ZBSIK_DMBTR,
  "부가가치세
  ZBSIK_MWSTS TYPE ZEDT13_209-ZBSIK_MWSTS,
  "세금코드
  ZBSIK_MWSKZ TYPE ZEDT13_209-ZBSIK_MWSKZ,
  "통화
  ZBSIK_WAERS TYPE ZEDT13_209-ZBSIK_WAERS,
  "텍스트
  ZBSIK_SGTXT TYPE ZEDT13_209-ZBSIK_SGTXT,
  "품목
  ZMSEG_ZEILE TYPE ZEDT13_209-ZMSEG_ZEILE,
  "지급 테이블
  "전표 번호
  ZBSIK_BELNR TYPE ZEDT13_210-ZBSIK_BELNR,
  "증빙일
  ZBSIK_BLDAT TYPE ZEDT13_210-ZBSIK_BLDAT,
  "전기일
  ZBSIK_BUDAT TYPE ZEDT13_210-ZBSIK_BUDAT,
  "사업자번호
  ZBSIK_GSBER TYPE ZEDT13_210-ZBSIK_GSBER,
  "지급기산일
  ZBSIK_ZFBDT TYPE ZEDT13_210-ZBSIK_ZFBDT,
  "공급가액 문자열
  ZBSIK_DMBTR_STR TYPE STRING,
  ZBSIK_MWSTS_STR TYPE STRING,

   END OF GS_PURCHASE .

DATA : GT_PURCHASE LIKE TABLE OF GS_PURCHASE .


*DATA : BEGIN OF GS_IR ,
*  송장 헤더, 아이템
*  회사코드
*  ZMSEG_BUKRS TYPE ZEDT13_209-ZMSEG_BUKRS,
*  구매오더번호
*  ZMSEG_EBELN TYPE ZEDT13_209-ZMSEG_EBELN,
*  거래금액
*  ZBSIK_DMBTR TYPE ZEDT13_209-ZBSIK_DMBTR,
*  부가가치세
*  ZBSIK_MWSTS TYPE ZEDT13_209-ZBSIK_MWSTS,
*  세금코드
*  ZBSIK_MWSKZ TYPE ZEDT13_209-ZBSIK_MWSKZ,
*  통화
*  ZBSIK_WAERS TYPE ZEDT13_209-ZBSIK_WAERS,
*  텍스트
*  ZBSIK_SGTXT TYPE ZEDT13_209-ZBSIK_SGTXT,
*  품목
*  ZMSEG_ZEILE TYPE ZEDT13_209-ZMSEG_ZEILE,
*  지급 테이블
*  전표 번호
*  ZBSIK_BELNR TYPE ZEDT13_210-ZBSIK_BELNR,
*  증빙일
*  ZBSIK_BLDAT TYPE ZEDT13_210-ZBSIK_BLDAT,
*  전기일
*  ZBSIK_BUDAT TYPE ZEDT13_210-ZBSIK_BUDAT,
*  사업자번호
*  ZBSIK_GSBER TYPE ZEDT13_210-ZBSIK_GSBER,
*  지급기산일
*  ZBSIK_ZFBDT TYPE ZEDT13_210-ZBSIK_ZFBDT,
*END OF GS_IR .
*
*DATA : GT_IR LIKE TABLE OF GS_IR .

DATA : BEGIN OF GS_HEADER .
  INCLUDE TYPE ZEDT13_208 .
DATA : END OF GS_HEADER .

DATA : GT_HEADER LIKE TABLE OF GS_HEADER .

DATA : BEGIN OF GS_ITEM .
  INCLUDE TYPE ZEDT13_209 .
DATA : END OF GS_ITEM .

DATA : GT_ITEM LIKE TABLE OF GS_ITEM .

DATA : BEGIN OF GS_GR .
  INCLUDE TYPE ZEDT13_207 .
DATA : END OF GS_GR .

DATA : GT_GR LIKE TABLE OF GS_GR .

DATA : GT_PURCHASE_SELECT LIKE TABLE OF GS_PURCHASE .
DATA : GO_EVENT TYPE REF TO EVENT .

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .

"삭제테이블
DATA : GT_ITEM_DEL LIKE TABLE OF GS_ITEM .