*&---------------------------------------------------------------------*
*&  Include           ZEDR13_HW001_TOP
*&---------------------------------------------------------------------*

" [조건] 7. 헤더가 없는 인터널 테이블
* 인터널 테이블 선언 (여러라인 조회하는 용도)
DATA : BEGIN OF GS_ORDER .
  INCLUDE TYPE ZEDT13_100 .
DATA : ZMTART_T TYPE STRING,
      ZSALE_T TYPE STRING,
      ZRET_T TYPE STRING,
      ZCOLOR TYPE C LENGTH 4,
      END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER .
* [실행조건] 6.인터널 테이블 선언 (출력  용도)
DATA : GT_ORDER_PRINT LIKE GT_ORDER .

DATA : BEGIN OF GS_DELIVERY .
  INCLUDE TYPE ZEDT13_101 .
DATA : ZCOLOR TYPE C LENGTH 4,
      END OF GS_DELIVERY .
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY .

* [실행조건] 6.인터널 테이블 선언 (출력  용도)
DATA : BEGIN OF GS_DELIVERY_PRINT .
  INCLUDE TYPE ZEDT13_101 .
DATA : END OF GS_DELIVERY_PRINT .
DATA : GT_DELIVERY_PRINT LIKE TABLE OF GS_DELIVERY_PRINT .

"필드카탈로그
DATA : GS_FIELDCAT TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT TYPE LVC_T_FCAT .

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .

" 소계 용 SORT
DATA : GS_SORT TYPE LVC_S_SORT .
DATA : GT_SORT TYPE LVC_T_SORT .

" 스크린 날짜 계산
DATA: LV_YEAR TYPE STRING ,
      LV_JAN_FIRST TYPE D,
      LV_JAN_FMT_STR TYPE STRING,
      LV_JAN_FMT TYPE DATS .

DATA : LV_DATUM_LOW  TYPE SY-DATUM,
  LV_DATUM_HIGH TYPE SY-DATUM.

" DOMAIN FIXED VAL가져오기
DATA: LT_DD07V_MTART TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_SALE_FG TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_RET_FG TYPE STANDARD TABLE OF DD07V,
      LS_DD07V TYPE DD07V.

" [조건] 0.테이블에서 가져오기
DATA : LV_ORDNO_LOW LIKE ZEDT13_100-ZORDNO .
DATA : LV_ORDNO_HIGH TYPE ZEDT13_100-ZORDNO .

DATA : OK_CODE TYPE SY-UCOMM .

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID .