*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_BP_SCR
*&---------------------------------------------------------------------*


TABLES : ZEDT13_201, ZEDT13_202 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .


SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_BUKRS MODIF ID M1 .
  PARAMETERS : P_BUKRS LIKE ZEDT13_202-ZLFB1_BUKRS MODIF ID M1 .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_KTOKK MODIF ID M1 .
  PARAMETERS : P_KTOKK  LIKE ZEDT13_201-ZLFA1_KTOKK MODIF ID M1 .
SELECTION-SCREEN END OF LINE .

SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD S_LIFNR MODIF ID M2 .
  SELECT-OPTIONS : S_LIFNR  FOR ZEDT13_201-ZLFA1_LIFNR MODIF ID M2 .
SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_BUKRS MODIF ID M2 .
  SELECT-OPTIONS : S_BUKRS FOR ZEDT13_202-ZLFB1_BUKRS MODIF ID M2 .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_CREATE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_LOOKUP RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .