*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_GR_TOP
*&---------------------------------------------------------------------*

DATA : OK_CODE TYPE SY-UCOMM .
DATA : GV_FOUND TYPE C LENGTH 1 .
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID .

DATA : GS_FIELDCAT TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT TYPE LVC_T_FCAT .

DATA : BEGIN OF GS_PURCHASE ,
  L_CHECK TYPE C LENGTH 1,
  ZEKKPO_EBELN TYPE ZEDT13_205-ZEKKPO_EBELN ,
  ZEKKO_BUKRS TYPE ZEDT13_204-ZEKKO_BUKRS ,
  ZEKPO_EBELP TYPE ZEDT13_205-ZEKPO_EBELP,
  ZEKKO_LIFNR TYPE ZEDT13_204-ZEKKO_LIFNR,
  ZEKKO_BEDAT TYPE ZEDT13_204-ZEKKO_BEDAT,
  ZEKPO_MATNR TYPE ZEDT13_205-ZEKPO_MATNR,
  ZMAKT_MAKTX TYPE ZEDT13_205-ZMAKT_MAKTX,
  ZEKPO_MENGE TYPE ZEDT13_205-ZEKPO_MENGE,
  ZEKPO_MEINS TYPE ZEDT13_205-ZEKPO_MEINS,
  ZEKPO_BPRME TYPE ZEDT13_205-ZEKPO_BPRME,
  ZEKKO_WAERS TYPE ZEDT13_204-ZEKKO_WAERS,
  ZEKPO_PRDAT TYPE ZEDT13_205-ZEKPO_PRDAT ,
  ZEKPO_WERKS TYPE ZEDT13_205-ZEKPO_WERKS,
  ZEKPO_LGORT TYPE ZEDT13_205-ZEKPO_LGORT,
   END OF GS_PURCHASE .

DATA : GT_PURCHASE LIKE TABLE OF GS_PURCHASE .

DATA : GT_PURCHASE_SELECT LIKE TABLE OF GS_PURCHASE .

DATA : BEGIN OF GS_HEADER .
  INCLUDE TYPE ZEDT13_206 .
DATA : END OF GS_HEADER .

DATA : GT_HEADER LIKE TABLE OF GS_HEADER .

DATA : BEGIN OF GS_ITEM .
  INCLUDE TYPE ZEDT13_207 .
DATA : END OF GS_ITEM .

DATA : GT_ITEM_DEL LIKE TABLE OF GS_ITEM .

DATA : GT_ITEM LIKE TABLE OF GS_ITEM .

DATA : GO_EVENT TYPE REF TO EVENT .

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .