*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_PO_TOP
*&---------------------------------------------------------------------*

DATA : OK_CODE TYPE SY-UCOMM .
DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID .

DATA : GS_FIELDCAT TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT TYPE LVC_T_FCAT .

"인터널 테이블
DATA : BEGIN OF GS_PURCHASE ,
  ZLFM1_MWSKZ TYPE ZEDT13_203-ZLFM1_MWSKZ ,
  ZEKKO_BUKRS TYPE ZEDT13_204-ZEKKO_BUKRS ,
  ZEKKO_EBELN TYPE ZEDT13_204-ZEKKO_EBELN ,
  ZEKKO_BEDAT TYPE ZEDT13_204-ZEKKO_BEDAT ,
  ZEKKO_WAERS TYPE ZEDT13_204-ZEKKO_WAERS ,
  ZEKPO_EBELP TYPE ZEDT13_205-ZEKPO_EBELP ,
  ZEKPO_MATNR TYPE ZEDT13_205-ZEKPO_MATNR ,
  ZMAKT_MAKTX TYPE ZEDT13_205-ZMAKT_MAKTX ,
  ZEKPO_MENGE TYPE ZEDT13_205-ZEKPO_MENGE ,
  ZEKPO_MEINS TYPE ZEDT13_205-ZEKPO_MEINS ,
  ZEKPO_BPRME TYPE ZEDT13_205-ZEKPO_BPRME ,
  ZEKPO_PRDAT TYPE ZEDT13_205-ZEKPO_PRDAT ,
  ZEKPO_WERKS TYPE ZEDT13_205-ZEKPO_WERKS ,
  ZEKPO_LGORT TYPE ZEDT13_205-ZEKPO_LGORT ,
END OF GS_PURCHASE .

DATA : GT_PURCHASE LIKE TABLE OF GS_PURCHASE .

DATA : BEGIN OF GS_HEADER_SAVE .
  INCLUDE TYPE ZEDT13_204 .
DATA : END OF GS_HEADER_SAVE .

DATA : GT_HEADER_SAVE LIKE TABLE OF GS_HEADER_SAVE .

DATA : BEGIN OF GS_ITEM_SAVE .
  INCLUDE TYPE ZEDT13_205 .
DATA : END OF GS_ITEM_SAVE .

DATA : GT_ITEM_SAVE LIKE TABLE OF GS_ITEM_SAVE .

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .

DATA : GO_EVENT_APPEND TYPE REF TO EVENT .

DATA : GO_EVENT_DELETE TYPE REF TO EVENT .

DATA : GO_EVENT_CREATE TYPE REF TO EVENT .

DATA : GV_FOUND TYPE C .