*&---------------------------------------------------------------------*
*& Report ZEDR13_PRACTICE005
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR13_PRACTICE005.


* 인터널 테이블 선언
DATA : BEGIN OF GS_EMPLOYEE .
  INCLUDE TYPE ZEDT13_004 .
DATA : END OF GS_EMPLOYEE .
DATA : GT_EMPLOYEE LIKE TABLE OF GS_EMPLOYEE .

DATA : BEGIN OF GS_SALARY .
  INCLUDE TYPE ZEDT13_007 .
DATA : END OF GS_SALARY .
DATA : GT_SALARY LIKE TABLE OF GS_SALARY .

DATA : BEGIN OF GS_EVALUATE .
  INCLUDE TYPE ZEDT13_006 .
DATA : END OF GS_EVALUATE .
DATA : GT_EVALUATE LIKE TABLE OF GS_EVALUATE .

" 날짜 계산을 위한 변수
DATA: LV_YEAR TYPE STRING ,
      LV_JAN_FIRST TYPE D,
      LV_JAN_FMT_STR TYPE STRING,
      LV_JAN_FMT TYPE DATS .

DATA : LV_DATUM_LOW  TYPE SY-DATUM,
  LV_DATUM_HIGH TYPE SY-DATUM.

DATA: lv_month TYPE STRING .
lv_month = sy-datum+4(2).

* 실제 테이블에서 가져오기

SELECT * FROM ZEDT13_004
INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE .
SELECT * FROM ZEDT13_007
INTO CORRESPONDING FIELDS OF TABLE GT_SALARY .
SELECT * FROM ZEDT13_006
INTO CORRESPONDING FIELDS OF TABLE GT_EVALUATE .


* SELECT-OPTIONS는 반드시 TABLES 필요
TABLES : ZEDT13_004 , ZEDT13_006 , ZEDT13_007 , ZEDT13_008 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZPERNR .
  SELECT-OPTIONS : S_ZPERNR FOR ZEDT13_004-ZPERNR .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD S_DATE MODIF ID M1 .
  SELECT-OPTIONS : S_DATE FOR ZEDT13_004-ZQDATE MODIF ID M1 .
SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_DCODE MODIF ID M1 .
  PARAMETERS : S_DCODE LIKE ZEDT13_004-ZDEPCODE MODIF ID M1 .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_YEAR MODIF ID M2 .
  PARAMETERS : P_YEAR LIKE ZEDT13_006-ZYEAR MODIF ID M2 .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_MONTH MODIF ID M2.
  PARAMETERS : P_MONTH LIKE ZEDT13_008-ZYEAR  MODIF ID M2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_EMPL RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_SAL  RADIOBUTTON GROUP R1 .
PARAMETERS : P_EVA RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .

" 퇴사상태
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME .
PARAMETERS : Z_QUIT AS CHECKBOX DEFAULT 'X' .
SELECTION-SCREEN END OF BLOCK B3 .



INITIALIZATION  .
" [SCREEN] 3. 주문일자  OR 배송일자
" 날짜 계산은 스크린 뜨기 전에 미리하기
LV_YEAR = SY-DATUM+0(4).
CONCATENATE LV_YEAR '0101' INTO LV_JAN_FIRST.

" 포맷팅된 문자열을 사용하여 날짜 형식으로 변환
LV_JAN_FMT = LV_JAN_FIRST.
RANGES GR_DATS FOR ZEDT13_100-ZJDATE .
LV_DATUM_HIGH = SY-DATUM.
" 달 마지막일 구하기
CALL FUNCTION 'RP_LAST_DAY_OF_MONTHS'
  EXPORTING
    DAY_IN            = LV_DATUM_HIGH
  IMPORTING
    LAST_DAY_OF_MONTH = LV_DATUM_HIGH .

GR_DATS-SIGN = 'I' .
GR_DATS-OPTION = 'BT' .
GR_DATS-LOW = LV_DATUM_LOW .
GR_DATS-HIGH = LV_DATUM_HIGH .
APPEND GR_DATS .


AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN .
  "체크박스 선택에 따른 제어
    IF SCREEN-GROUP1 = 'M1' .
      IF P_EMPL = 'X' .
        SCREEN-ACTIVE = '1'.
        IF S_DATE[] IS INITIAL.
          S_DATE-SIGN = 'I'.
          S_DATE-OPTION = 'BT'.
          S_DATE-HIGH = LV_DATUM_HIGH.
          S_DATE-LOW = LV_JAN_FIRST.
          APPEND S_DATE.
       ENDIF .
      ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
    IF SCREEN-GROUP1 = 'M2' .
      IF P_SAL = 'X' OR P_EVA = 'X' .
        SCREEN-ACTIVE = '1'.
        P_YEAR = LV_YEAR .
        P_MONTH = sy-datum+4(2) .
       ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.