*&---------------------------------------------------------------------*
*& Report ZEDR13_PRACTICE005
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR13_PRACTICE005.


* 인터널 테이블 선언
DATA : BEGIN OF GS_EMPLOYEE .
  INCLUDE TYPE ZEDT13_004 .
DATA : ZQFLAG_T TYPE STRING ,
      ZDEPCODE_T TYPE STRING ,
      ZDEPRANK_T TYPE STRING ,
      ZEDATE_EXPAND TYPE STRING ,
      ZPNAME TYPE ZEDT13_005-ZPNAME,
      ZGENDER TYPE ZEDT13_005-ZGENDER ,
      ZADDRESS TYPE ZEDT13_005-ZADDRESS ,
      ZBANKCODE TYPE ZEDT13_008-ZBANKCODE ,
      ZBANKCODE_T TYPE STRING ,
      ZACCOUNT  TYPE ZEDT13_008-ZACCOUNT ,
      END OF GS_EMPLOYEE .

DATA : GT_EMPLOYEE LIKE TABLE OF GS_EMPLOYEE .
DATA : GT_EMPLOYEE_PRINT LIKE GT_EMPLOYEE .

" 06번 테이블 그 자체를 가져오는 인터널 테이블
DATA : BEGIN OF GS_EVA06 .
  INCLUDE TYPE  ZEDT13_006 .
DATA : END OF GS_EVA06 .
DATA : GT_EVA06 LIKE TABLE OF GS_EVA06 .


DATA : BEGIN OF GS_EVALUATE .
  INCLUDE TYPE ZEDT13_004 .
DATA : ZSALARY TYPE ZEDT13_008-ZSALARY ,
      ZMONTH TYPE ZEDT13_007-ZMON01 ,
      ZRANK TYPE ZEDT13_006-ZRANK,
      ZDEPCODE_T TYPE STRING ,
 END OF GS_EVALUATE .
DATA : GT_EVALUATE LIKE TABLE OF GS_EVALUATE .
DATA : GT_EVALUATE_PRINT LIKE GT_EVALUATE .

DATA : BEGIN OF GS_SALARY .
  INCLUDE TYPE ZEDT13_007.
DATA :
      ZQFLAG TYPE ZEDT13_004-ZQFLAG ,
      ZSALARY TYPE ZEDT13_008-ZSALARY ,
      ZRANK TYPE ZEDT13_006-ZRANK,
       END OF GS_SALARY .
DATA : GT_SALARY LIKE TABLE OF GS_SALARY .

"field catalog
DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV .
DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV .

" 사원번호, datbi range table
DATA : LV_PERNR_LOW LIKE ZEDT13_004-ZPERNR ,
  LV_PERNR_HIGH LIKE ZEDT13_004-ZPERNR.
DATA : LV_DATBI_LOW LIKE ZEDT13_004-ZPERNR ,
      LV_DATBI_HIGH LIKE ZEDT13_004-ZPERNR .

" 날짜 계산을 위한 변수
DATA: LV_YEAR TYPE STRING ,
      LV_JAN_FIRST TYPE D,
      LV_JAN_FMT_STR TYPE STRING,
      LV_JAN_FMT TYPE DATS .

DATA : LV_DATUM_LOW  TYPE SY-DATUM,
  LV_DATUM_HIGH TYPE SY-DATUM.

DATA: lv_month TYPE STRING .
lv_month = sy-datum+4(2).

DATA : LV_MONTH_FIELD(50) TYPE C .
DATA : LV_MONTH_FIELD_CAT(50) TYPE C .
DATA : LV_ZMONTH(50) TYPE C .


"DOMAIN FIXED VAL
DATA: LT_DD07V_QUIT TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_DEPRANK TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_GENDER TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_BANK TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_DEPCODE TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_DEPNAME TYPE STANDARD TABLE OF DD07V,
      LS_DD07V TYPE DD07V.

CALL FUNCTION 'GET_DOMAIN_VALUES'
  EXPORTING
    DOMNAME         = 'ZQFLAG13'
    TEXT            = 'X'
  TABLES
    VALUES_TAB      = LT_DD07V_QUIT
  EXCEPTIONS
    VALUE_NOT_FOUND = 1
    OTHERS          = 2.

CALL FUNCTION 'GET_DOMAIN_VALUES'
  EXPORTING
    DOMNAME         = 'ZDEPRANK13'
    TEXT            = 'X'
  TABLES
    VALUES_TAB      = LT_DD07V_DEPRANK
  EXCEPTIONS
    VALUE_NOT_FOUND = 1
    OTHERS          = 2.


CALL FUNCTION 'GET_DOMAIN_VALUES'
  EXPORTING
    DOMNAME         = 'ZGENDER13'
    TEXT            = 'X'
  TABLES
    VALUES_TAB      = LT_DD07V_GENDER
  EXCEPTIONS
    VALUE_NOT_FOUND = 1
    OTHERS          = 2.

CALL FUNCTION 'GET_DOMAIN_VALUES'
  EXPORTING
    DOMNAME         = 'ZBANKCODE13'
    TEXT            = 'X'
  TABLES
    VALUES_TAB      = LT_DD07V_BANK
  EXCEPTIONS
    VALUE_NOT_FOUND = 1
    OTHERS          = 2.

CALL FUNCTION 'GET_DOMAIN_VALUES'
  EXPORTING
    DOMNAME         = 'ZDEPCODE13'
    TEXT            = 'X'
  TABLES
    VALUES_TAB      = LT_DD07V_DEPCODE
  EXCEPTIONS
    VALUE_NOT_FOUND = 1
    OTHERS          = 2.




* 실제 테이블에서 가져오기
SELECT * FROM ZEDT13_004
INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE .
SELECT * FROM ZEDT13_007
INTO CORRESPONDING FIELDS OF TABLE GT_SALARY .
SELECT * FROM ZEDT13_006
INTO CORRESPONDING FIELDS OF TABLE GT_EVALUATE .


* SELECT-OPTIONS는 반드시 TABLES 필요
TABLES : ZEDT13_004 , ZEDT13_006 , ZEDT13_007 , ZEDT13_008 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZPERNR .
  SELECT-OPTIONS : S_ZPERNR FOR ZEDT13_004-ZPERNR .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD S_DATE MODIF ID M1 .
  SELECT-OPTIONS : S_DATE FOR ZEDT13_004-DATBI MODIF ID M1 .
SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_DCODE MODIF ID M1 .
  PARAMETERS : P_DCODE LIKE ZEDT13_004-ZDEPCODE MODIF ID M1 .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_YEAR MODIF ID M2 .
  PARAMETERS : P_YEAR LIKE ZEDT13_006-ZYEAR MODIF ID M2 .
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_MONTH MODIF ID M2.
  PARAMETERS : P_MONTH LIKE ZEDT13_008-ZYEAR  MODIF ID M2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_EMPL RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_SAL  RADIOBUTTON GROUP R1 .
PARAMETERS : P_EVA RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .

" 퇴사상태
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME .
PARAMETERS : Z_QUIT AS CHECKBOX DEFAULT 'X' .
SELECTION-SCREEN END OF BLOCK B3 .

INITIALIZATION  .
" [SCREEN] 3. 주문일자  OR 배송일자
" 날짜 계산은 스크린 뜨기 전에 미리하기
LV_YEAR = SY-DATUM+0(4).
CONCATENATE LV_YEAR '0101' INTO LV_JAN_FIRST.

" 포맷팅된 문자열을 사용하여 날짜 형식으로 변환
LV_JAN_FMT = LV_JAN_FIRST.
RANGES GR_DATS FOR ZEDT13_100-ZJDATE .
LV_DATUM_HIGH = SY-DATUM.
" 달 마지막일 구하기
CALL FUNCTION 'RP_LAST_DAY_OF_MONTHS'
  EXPORTING
    DAY_IN            = LV_DATUM_HIGH
  IMPORTING
    LAST_DAY_OF_MONTH = LV_DATUM_HIGH .

GR_DATS-SIGN = 'I' .
GR_DATS-OPTION = 'BT' .
GR_DATS-LOW = LV_DATUM_LOW .
GR_DATS-HIGH = LV_DATUM_HIGH .
APPEND GR_DATS .


AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN .
  "체크박스 선택에 따른 제어
    IF SCREEN-GROUP1 = 'M1' .
      IF P_EMPL = 'X' .
        SCREEN-ACTIVE = '1'.
        IF S_DATE[] IS INITIAL.
          S_DATE-SIGN = 'I'.
          S_DATE-OPTION = 'BT'.
          S_DATE-HIGH = LV_DATUM_HIGH.
          S_DATE-LOW = LV_JAN_FIRST.
          APPEND S_DATE.
       ENDIF .
      ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
    IF SCREEN-GROUP1 = 'M2' .
      IF P_SAL = 'X' OR P_EVA = 'X' .
        SCREEN-ACTIVE = '1'.
        P_YEAR = LV_YEAR .
        P_MONTH = sy-datum+4(2) .
        call function 'CONVERSION_EXIT_ALPHA_OUTPUT'
          exporting
               input   = P_MONTH
          importing
              output   = P_MONTH  .

       CONCATENATE 'ZMON'P_MONTH  INTO LV_ZMONTH .
       CONCATENATE P_MONTH  '월 지급액' INTO LV_MONTH_FIELD_CAT .
       ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.

START-OF-SELECTION .
  PERFORM GET_DATA .
END-OF-SELECTION .
  PERFORM ALV_DISPLAY .

FORM ALV_DISPLAY .
  IF P_EMPL = 'X' .
    PERFORM FIELD_CATALOG .
    PERFORM CALL_ALV .

  ELSEIF P_EVA = 'X' .
    PERFORM FIELD_CATALOG_EVA .
    PERFORM CALL_ALV .

  ENDIF .
ENDFORM .




FORM GET_DATA .

  LV_PERNR_LOW = S_ZPERNR-LOW .
  LV_PERNR_HIGH = S_ZPERNR-HIGH .

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT         = LV_PERNR_LOW
    IMPORTING
      OUTPUT        = LV_PERNR_LOW .
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT         = LV_PERNR_HIGH
    IMPORTING
      OUTPUT        = LV_PERNR_HIGH .

  LV_DATBI_LOW = S_DATE-LOW .
  LV_DATBI_HIGH = S_DATE-HIGH .

  CALL FUNCTION 'CONVERSION_EXIT_PDATE_OUTPUT'
    EXPORTING
      INPUT = LV_DATBI_LOW
    IMPORTING
      OUTPUT = LV_DATBI_LOW .

  CALL FUNCTION 'CONVERSION_EXIT_PDATE_OUTPUT'
    EXPORTING
      INPUT = LV_DATBI_HIGH
    IMPORTING
      OUTPUT = LV_DATBI_HIGH .



  RANGES : GR_EQDATE FOR ZEDT13_004-DATBI .
  RANGES : GR_PERNR FOR ZEDT13_004-ZPERNR .

  CLEAR GR_EQDATE .
  GR_EQDATE-SIGN = 'I' .
  GR_EQDATE-OPTION = 'BT' .
  GR_EQDATE-LOW = S_DATE-LOW .
  GR_EQDATE-HIGH = S_DATE-HIGH .
  APPEND GR_EQDATE .

  CLEAR GR_PERNR .
  GR_PERNR-SIGN = 'I' .
  GR_PERNR-OPTION = 'BT' .
  GR_PERNR-LOW = LV_PERNR_LOW .
  GR_PERNR-HIGH = LV_PERNR_HIGH .
  APPEND GR_PERNR
  .
  "사원정보 가져오기
  " 재직 클릭한  경우
  IF P_EMPL = 'X' .

   IF Z_QUIT = 'X' .
      IF P_DCODE IS INITIAL AND S_ZPERNR[] IS INITIAL.
        SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
           FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
          INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
        WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND ZQFLAG <> 'X' .

      ELSEIF P_DCODE IS INITIAL AND S_ZPERNR[] IS NOT INITIAL .
        SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
           FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
          INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
          WHERE (  ZEDT13_004~ZPERNR IN GR_PERNR ) AND ZQFLAG <> 'X' .

      ELSEIF P_DCODE IS NOT INITIAL AND S_ZPERNR[] IS INITIAL.
        SELECT * INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
          FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
          INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
        WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND
            ( ZEDT13_004~ZDEPCODE EQ P_DCODE )  AND ZQFLAG <> 'X' .

      ELSEIF P_DCODE IS NOT INITIAL AND S_ZPERNR[] IS NOT INITIAL.
         SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
          INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
        INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
        WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND  (  ZEDT13_004~ZPERNR IN GR_PERNR ) AND
            ( ZEDT13_004~ZDEPCODE EQ P_DCODE )  AND ZQFLAG <> 'X' .
      ENDIF .


  " 재직 클릭 안한 경우
  ELSE .
    IF P_DCODE IS INITIAL AND S_ZPERNR[] IS INITIAL.
      SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
      WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) .

    ELSEIF P_DCODE IS INITIAL AND S_ZPERNR[] IS NOT INITIAL .
      SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
      WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND ( ZEDT13_004~ZPERNR IN GR_PERNR ).

    ELSEIF P_DCODE IS NOT INITIAL AND S_ZPERNR[] IS INITIAL.
      SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
      WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND
          ( ZEDT13_004~ZDEPCODE EQ P_DCODE ) .

    ELSEIF P_DCODE IS NOT INITIAL AND S_ZPERNR[] IS NOT INITIAL.
       SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_005 ON ZEDT13_004~ZPERNR = ZEDT13_005~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EMPLOYEE
      WHERE ( ZEDT13_004~DATBI IN GR_EQDATE ) AND
          ( ZEDT13_004~ZPERNR IN GR_PERNR ) .
    ENDIF .
  ENDIF .
ENDIF .

IF P_EVA = 'X' .
  IF S_ZPERNR[] IS INITIAL.
    SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_006 ON ZEDT13_006~ZPERNR = ZEDT13_004~ZPERNR
      INNER JOIN ZEDT13_007 ON ZEDT13_007~ZPERNR = ZEDT13_004~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EVALUATE .

  ELSE .
    SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_006 ON ZEDT13_006~ZPERNR = ZEDT13_004~ZPERNR
      INNER JOIN ZEDT13_007 ON ZEDT13_007~ZPERNR = ZEDT13_004~ZPERNR
        INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_EVALUATE .
  ENDIF .


ENDIF .

IF P_SAL = 'X' .
*   평가 데이터 있는지 확인

  SELECT * FROM ZEDT13_006  INTO CORRESPONDING FIELDS OF TABLE GT_EVA06 WHERE ZYEAR = '2024' .
  DATA : LV_TOTAL TYPE I.
  DESCRIBE TABLE GT_EVA06 LINES LV_TOTAL.

  IF LV_TOTAL <> 0 .
*     1. 퇴사하지 않은 직원만 인터널 테이블에 담아온다. 2. 직원 인터널 테이블을 돌면서 SINGLE 라인으로 디비에 MODIFY 시킨다
    IF S_ZPERNR[] IS INITIAL.
      SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INNER JOIN ZEDT13_006 ON ZEDT13_004~ZPERNR = ZEDT13_006~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_SALARY WHERE ZEDT13_004~ZQFLAG <> 'X' .

    ELSE .
      SELECT * FROM ZEDT13_004 INNER JOIN ZEDT13_008 ON ZEDT13_004~ZPERNR = ZEDT13_008~ZPERNR
      INNER JOIN ZEDT13_006 ON ZEDT13_004~ZPERNR = ZEDT13_006~ZPERNR
      INTO CORRESPONDING FIELDS OF TABLE GT_SALARY WHERE ZQFLAG <> 'X' AND ZEDT13_004~ZPERNR IN GR_PERNR .

    ENDIF .


    DATA : BEGIN OF LS_SALARY .
      INCLUDE TYPE ZEDT13_007 .
    DATA : END OF LS_SALARY .
    LOOP AT GT_SALARY INTO GS_SALARY .
      LS_SALARY-ZPERNR = GS_SALARY-ZPERNR .
      LS_SALARY-ZYEAR = LV_YEAR .
      LS_SALARY-AENAME = sy-uname .
      LS_SALARY-AEZEIT = SY-UZEIT .
      LS_SALARY-AEDATE = SY-DATUM .



      CASE LV_ZMONTH .
        WHEN 'ZMON01' .
         LS_SALARY-ZMON01 = ( GS_SALARY-ZSALARY ) / 12 .
         IF GS_SALARY-ZRANK = 'A' .
           LS_SALARY-ZMON01 = ( LS_SALARY-ZMON01 + 500 ) .
         ENDIF .


        WHEN 'ZMON02' .
          LS_SALARY-ZMON02 = ( GS_SALARY-ZSALARY ) / 12 .
           IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON02 = ( LS_SALARY-ZMON02 + 500 ) .
           ENDIF .

        WHEN 'ZMON03' .
          LS_SALARY-ZMON03 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON03 = ( LS_SALARY-ZMON03 + 500 ) .
           ENDIF .

        WHEN 'ZMON04' .
          LS_SALARY-ZMON04 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON04 = ( LS_SALARY-ZMON04 + 500 ) .
           ENDIF .

        WHEN 'ZMON05' .
          LS_SALARY-ZMON05 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON05 = ( LS_SALARY-ZMON05 + 500 ) .
           ENDIF .

        WHEN 'ZMON06' .
          LS_SALARY-ZMON06 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON06 = ( LS_SALARY-ZMON06 + 500 ) .
           ENDIF .

        WHEN 'ZMON07' .
          LS_SALARY-ZMON07 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON07 = ( LS_SALARY-ZMON07 + 500 ) .
           ENDIF .

        WHEN 'ZMON08' .
          LS_SALARY-ZMON08 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON08 = ( LS_SALARY-ZMON08 + 500 ) .
           ENDIF .

        WHEN 'ZMON09' .
          LS_SALARY-ZMON09 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON09 = ( LS_SALARY-ZMON09 + 500 ) .
           ENDIF .

        WHEN 'ZMON10' .
          LS_SALARY-ZMON10 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON10 = ( LS_SALARY-ZMON10 + 500 ) .
           ENDIF .

        WHEN 'ZMON11' .
          LS_SALARY-ZMON11 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON11 = ( LS_SALARY-ZMON11 + 500 ) .
           ENDIF .

        WHEN 'ZMON12' .
          LS_SALARY-ZMON12 = ( GS_SALARY-ZSALARY ) / 12 .
          IF GS_SALARY-ZRANK = 'A' .
            LS_SALARY-ZMON12 = ( LS_SALARY-ZMON12 + 500 ) .
           ENDIF .

      ENDCASE .
      MODIFY ZEDT13_007 FROM LS_SALARY .
      IF SY-SUBRC <> 0 .
          WRITE : / '업데이트 실패' .
         LEAVE PROGRAM.
      ENDIF .
    ENDLOOP .

  ENDIF .

  WRITE : / '월급이 지급되었습니다' .



ENDIF .


ENDFORM .


FORM CALL_ALV .


IF P_EMPL = 'X' .
  IF GT_EMPLOYEE IS NOT INITIAL.

  LOOP AT GT_EMPLOYEE INTO GS_EMPLOYEE .
    READ TABLE LT_DD07V_QUIT  WITH KEY DOMVALUE_L = GS_EMPLOYEE-ZQFLAG INTO LS_DD07V .
    GS_EMPLOYEE-ZQFLAG_T = LS_DD07V-DDTEXT .
    MODIFY GT_EMPLOYEE FROM GS_EMPLOYEE TRANSPORTING ZQFLAG_T WHERE ZPERNR = GS_EMPLOYEE-ZPERNR .
  ENDLOOP .

  LOOP AT GT_EMPLOYEE INTO GS_EMPLOYEE .
    READ TABLE LT_DD07V_DEPRANK  WITH KEY DOMVALUE_L = GS_EMPLOYEE-ZDEPRANK INTO LS_DD07V .
    GS_EMPLOYEE-ZDEPRANK_T = LS_DD07V-DDTEXT .
    MODIFY GT_EMPLOYEE FROM GS_EMPLOYEE TRANSPORTING ZDEPRANK_T WHERE ZPERNR = GS_EMPLOYEE-ZPERNR .
  ENDLOOP .

   LOOP AT GT_EMPLOYEE INTO GS_EMPLOYEE .
    READ TABLE LT_DD07V_GENDER  WITH KEY DOMVALUE_L = GS_EMPLOYEE-ZGENDER INTO LS_DD07V .
    GS_EMPLOYEE-ZGENDER = LS_DD07V-DDTEXT .
    MODIFY GT_EMPLOYEE FROM GS_EMPLOYEE TRANSPORTING ZGENDER WHERE ZPERNR = GS_EMPLOYEE-ZPERNR .
  ENDLOOP .

  LOOP AT GT_EMPLOYEE INTO GS_EMPLOYEE .
    READ TABLE LT_DD07V_DEPCODE  WITH KEY DOMVALUE_L = GS_EMPLOYEE-ZDEPCODE INTO LS_DD07V .
    GS_EMPLOYEE-ZDEPCODE_T = LS_DD07V-DDTEXT .
    MODIFY GT_EMPLOYEE FROM GS_EMPLOYEE TRANSPORTING ZDEPCODE_T WHERE ZPERNR = GS_EMPLOYEE-ZPERNR .
  ENDLOOP .

  LOOP AT GT_EMPLOYEE INTO GS_EMPLOYEE .
    READ TABLE LT_DD07V_BANK  WITH KEY DOMVALUE_L = GS_EMPLOYEE-ZBANKCODE INTO LS_DD07V .
    GS_EMPLOYEE-ZBANKCODE_T = LS_DD07V-DDTEXT .
    MODIFY GT_EMPLOYEE FROM GS_EMPLOYEE TRANSPORTING ZBANKCODE_T WHERE ZPERNR = GS_EMPLOYEE-ZPERNR .
  ENDLOOP .

  GT_EMPLOYEE_PRINT[] = GT_EMPLOYEE[].
ENDIF.
CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
        IT_FIELDCAT = GT_FIELDCAT
        I_STRUCTURE_NAME = 'GT_EMPLOYEE'
      TABLES
        T_OUTTAB = GT_EMPLOYEE_PRINT .
ELSEIF P_EVA = 'X' .
  LOOP AT GT_EVALUATE INTO GS_EVALUATE .
    READ TABLE LT_DD07V_DEPCODE   WITH KEY DOMVALUE_L = GS_EVALUATE-ZDEPCODE INTO LS_DD07V .
    GS_EVALUATE-ZDEPCODE_T = LS_DD07V-DDTEXT .
    MODIFY GT_EVALUATE FROM GS_EVALUATE TRANSPORTING ZDEPCODE_T WHERE ZPERNR = GS_EVALUATE-ZPERNR .
  ENDLOOP .
  GT_EVALUATE_PRINT[] = GT_EVALUATE[].
    CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
      EXPORTING
        IT_FIELDCAT = GT_FIELDCAT
        I_STRUCTURE_NAME = 'GT_EVALUATE'
      TABLES
        T_OUTTAB = GT_EVALUATE_PRINT .
ENDIF .
ENDFORM .

FORM FIELD_CATALOG .
  CLEAR : GS_FIELDCAT , GT_FIELDCAT .
  GS_FIELDCAT-COL_POS = 1 .
  GS_FIELDCAT-FIELDNAME = 'ZPERNR' .
  GS_FIELDCAT-SELTEXT_M = '사원번호' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 2 .
  GS_FIELDCAT-FIELDNAME = 'ZPNAME' .
  GS_FIELDCAT-SELTEXT_M = '사원이름' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 3 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPCODE' .
  GS_FIELDCAT-SELTEXT_M = '부서코드' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 4 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPCODE_T' .
  GS_FIELDCAT-SELTEXT_M = '부서명' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 5 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPRANK_T' .
  GS_FIELDCAT-SELTEXT_M = '직급명' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 6 .
  GS_FIELDCAT-FIELDNAME = 'ZEDATE' .
  GS_FIELDCAT-SELTEXT_M = '입사일자' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 7 .
  GS_FIELDCAT-FIELDNAME = 'ZQFLAG_T' .
  GS_FIELDCAT-SELTEXT_M = '퇴사상태' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 8 .
  GS_FIELDCAT-FIELDNAME = 'ZGENDER_T' .
  GS_FIELDCAT-SELTEXT_M = '성별' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 9 .
  GS_FIELDCAT-FIELDNAME = 'ZADDRESS' .
  GS_FIELDCAT-SELTEXT_M = '주소' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 10 .
  GS_FIELDCAT-FIELDNAME = 'ZBANKCODE_T' .
  GS_FIELDCAT-SELTEXT_M = '은행명' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

   CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 11 .
  GS_FIELDCAT-FIELDNAME = 'ZACCOUNT' .
  GS_FIELDCAT-SELTEXT_M = '계좌번호' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .
ENDFORM .


FORM FIELD_CATALOG_EVA .
  CLEAR : GS_FIELDCAT , GT_FIELDCAT .
  GS_FIELDCAT-COL_POS = 1 .
  GS_FIELDCAT-FIELDNAME = 'ZPERNR' .
  GS_FIELDCAT-SELTEXT_M = '사원번호' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 2 .
  GS_FIELDCAT-FIELDNAME = 'ZPNAME' .
  GS_FIELDCAT-SELTEXT_M = '사원이름' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 3 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPCODE' .
  GS_FIELDCAT-SELTEXT_M = '부서코드' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 4 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPCODE_T' .
  GS_FIELDCAT-SELTEXT_M = '부서명' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 5 .
  GS_FIELDCAT-FIELDNAME = 'ZDEPRANK' .
  GS_FIELDCAT-SELTEXT_M = '직급' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 6 .
  GS_FIELDCAT-FIELDNAME = 'ZEDATE' .
  GS_FIELDCAT-SELTEXT_M = '입사일자' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 7 .
  GS_FIELDCAT-FIELDNAME = 'ZSALARY' .
  GS_FIELDCAT-SELTEXT_M = '계약금액' .
  GS_FIELDCAT-CURRENCY = 'KRW' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 8 .
  GS_FIELDCAT-FIELDNAME = 'ZRANK' .
  GS_FIELDCAT-SELTEXT_M = '평가등급' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 9 .
  GS_FIELDCAT-FIELDNAME = LV_ZMONTH .
  GS_FIELDCAT-SELTEXT_M = LV_MONTH_FIELD_CAT .
  GS_FIELDCAT-CURRENCY = 'KRW' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

ENDFORM .