*&---------------------------------------------------------------------*
*& Report ZEDR13_HW001
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR13_HW001.

* 인터널 테이블 선언
DATA : BEGIN OF GS_ORDER .
  INCLUDE TYPE ZEDT13_100 .
DATA : END OF GS_ORDER .
DATA : GT_ORDER LIKE TABLE OF GS_ORDER .

DATA : BEGIN OF GS_DELIVERY .
  INCLUDE TYPE ZEDT13_101 .
DATA : END OF GS_DELIVERY .
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY .

* 실제 테이블에서 가져오기

SELECT * FROM ZEDT13_100
INTO CORRESPONDING FIELDS OF TABLE GT_ORDER .

SELECT * FROM ZEDT13_101
INTO CORRESPONDING FIELDS OF TABLE GT_DELIVERY .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_ORDNO .
  PARAMETERS: P_ORDNO LIKE ZEDT13_100-ZORDNO.
  SELECTION-SCREEN POSITION 30.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_ORDTO .
  PARAMETERS: P_ORDTO LIKE ZEDT13_100-ZORDNO.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_ZID .
  PARAMETERS : P_ZID LIKE ZEDT13_100-ZIDCODE .
  SELECTION-SCREEN POSITION 30.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_IDTO .
  PARAMETERS: P_IDTO LIKE ZEDT13_100-ZIDCODE .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_MATNR .
  PARAMETERS : P_MATNR LIKE ZEDT13_100-ZMATNR .
  SELECTION-SCREEN POSITION 30.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_MATTO .
  PARAMETERS: P_MATTO LIKE ZEDT13_100-ZMATNR .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_ZJDATE.
  PARAMETERS : P_ZJDATE LIKE ZEDT13_100-ZJDATE .
  SELECTION-SCREEN POSITION 30.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_JDATTO .
  PARAMETERS: P_JDATTO LIKE ZEDT13_100-ZJDATE .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_RORD RADIOBUTTON GROUP R1 DEFAULT 'X' .
PARAMETERS : P_RDELV  RADIOBUTTON GROUP R1.
SELECTION-SCREEN END OF BLOCK B2 .