*&---------------------------------------------------------------------*
*& Report ZEDR13_EX001
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZEDR13_EX001 MESSAGE-ID ZMED13_100 .

" [조건] 7. 헤더가 없는 인터널 테이블
* 인터널 테이블 선언 (여러라인 조회하는 용도)
DATA : BEGIN OF GS_ORDER .
  INCLUDE TYPE ZEDT13_100 .
DATA : END OF GS_ORDER .
DATA : GT_ORDER LIKE TABLE OF GS_ORDER .
* 인터널 테이블 선언 (출력  용도)
DATA : BEGIN OF GS_ORDER_PRINT .
  INCLUDE TYPE ZEDT13_100 .
DATA : END OF GS_ORDER_PRINT .
DATA : GT_ORDER_PRINT LIKE TABLE OF GS_ORDER_PRINT .

DATA : BEGIN OF GS_DELIVERY .
  INCLUDE TYPE ZEDT13_101 .
DATA : END OF GS_DELIVERY .
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY .

DATA : BEGIN OF GS_DELIVERY_PRINT .
  INCLUDE TYPE ZEDT13_101 .
DATA : END OF GS_DELIVERY_PRINT .
DATA : GT_DELIVERY_PRINT LIKE TABLE OF GS_DELIVERY_PRINT .


DATA : GS_FIELDCAT TYPE SLIS_FIELDCAT_ALV .
DATA : GT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV .

DATA: LV_YEAR TYPE STRING ,
      LV_JAN_FIRST TYPE D,
      LV_JAN_FMT_STR TYPE STRING,
      LV_JAN_FMT TYPE DATS .

DATA : LV_DATUM_LOW  TYPE SY-DATUM,
  LV_DATUM_HIGH TYPE SY-DATUM.




* SELECT-OPTIONS는 반드시 TABLES 필요
TABLES : ZEDT13_100 , ZEDT13_101 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .


SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZORDNO .
  SELECT-OPTIONS : S_ZORDNO FOR ZEDT13_100-ZORDNO .
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_ZID .
  PARAMETERS : P_ZID LIKE ZEDT13_100-ZIDCODE .
SELECTION-SCREEN END OF LINE .
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZMATNR .
  SELECT-OPTIONS : S_ZMATNR FOR ZEDT13_100-ZMATNR .
SELECTION-SCREEN END OF LINE.
" 주문일자와 관련된 COMMENT 및 SELECT-OPTIONS 함께 배치
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZJDATE MODIF ID M1.
  SELECT-OPTIONS : S_ZJDATE FOR ZEDT13_100-ZJDATE MODIF ID M1.
SELECTION-SCREEN END OF LINE.

" 배송일자와 관련된 COMMENT 및 SELECT-OPTIONS 함께 배치
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD S_ZDDATE MODIF ID M2.
  SELECT-OPTIONS : S_ZDDATE FOR ZEDT13_101-ZDDATE MODIF ID M2.
SELECTION-SCREEN END OF LINE.
SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_RORD RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_RDELV  RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .

" [SCREEN] 2. 반품내역포함엔 체크박스로 기본적으로 X표기 기표
SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME .
PARAMETERS : Z_RETCH AS CHECKBOX DEFAULT 'X' .
SELECTION-SCREEN END OF BLOCK B3 .



" [SCREEN] 4. 주문번호 또는 회원 ID가 필수적으로 입력되어야 한다. 둘다 입력이 되지 않으면 ERROR를 뿌리며 레포트가 실행되지 않는다
" [SCREEN] 5. 주문번호 입력 시에는 주문일자 입력하지 않아도 되지만 회원ID  입력시에는 주문일자 반드시 입력
IF ( P_ZID IS NOT INITIAL ) AND ( S_ZORDNO IS INITIAL )  AND ( S_ZJDATE IS INITIAL ) .
  MESSAGE E001 .
ENDIF .
IF ( S_ZORDNO IS INITIAL ) AND  ( P_ZID IS INITIAL ) .
  MESSAGE E000 .
ENDIF .

"[조건] 5. intial 사용
INITIALIZATION  .
" [SCREEN] 3. 주문일자  OR 배송일자
" 날짜 계산은 스크린 뜨기 전에 미리하기
LV_YEAR = SY-DATUM+0(4).
CONCATENATE LV_YEAR '0101' INTO LV_JAN_FIRST.

" 포맷팅된 문자열을 사용하여 날짜 형식으로 변환
LV_JAN_FMT = LV_JAN_FIRST.
" [조건] 4. range변수 한번 이상
RANGES GR_DATS FOR ZEDT13_100-ZJDATE .
LV_DATUM_HIGH = SY-DATUM.
" 달 마지막일 구하기
CALL FUNCTION 'RP_LAST_DAY_OF_MONTHS'
  EXPORTING
    DAY_IN            = LV_DATUM_HIGH
  IMPORTING
    LAST_DAY_OF_MONTH = LV_DATUM_HIGH .

GR_DATS-SIGN = 'I' .
GR_DATS-OPTION = 'BT' .
GR_DATS-LOW = LV_DATUM_LOW .
GR_DATS-HIGH = LV_DATUM_HIGH .
APPEND GR_DATS .


AT SELECTION-SCREEN OUTPUT.
  LOOP AT SCREEN .
    " [SCREEN] #1. 주문내역, 배송내역 라디오버튼 클릭마다 주문일자 , 배송날짜 다르게 표기하게
    IF SCREEN-GROUP1 = 'M1' .
      IF P_RORD = 'X' .
        SCREEN-ACTIVE = '1'.
        IF S_ZJDATE[] IS INITIAL.
          S_ZJDATE-SIGN = 'I'.
          S_ZJDATE-OPTION = 'BT'.
          S_ZJDATE-HIGH = LV_DATUM_HIGH.
          S_ZJDATE-LOW = LV_JAN_FIRST.
          APPEND S_ZJDATE.
       ENDIF .
      ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
    IF SCREEN-GROUP1 = 'M2' .
      IF P_RDELV = 'X' .
        SCREEN-ACTIVE = '1'.
        IF S_ZDDATE[] IS INITIAL.
          S_ZDDATE-SIGN = 'I'.
          S_ZDDATE-OPTION = 'BT'.
          S_ZDDATE-HIGH = LV_DATUM_HIGH.
          S_ZDDATE-LOW = LV_JAN_FIRST.
          APPEND S_ZDDATE.
        ENDIF .
       ELSE .
        SCREEN-ACTIVE = '0' .
      ENDIF .
      MODIFY SCREEN.
    ENDIF.
  ENDLOOP.



" [조건] 5. START-OF-SELEC~ 사용
START-OF-SELECTION .
  PERFORM GET_DATA .
END-OF-SELECTION .
  PERFORM ALV_DISPLAY .

FORM ALV_DISPLAY .
  PERFORM FIELD_CATALOG .
  PERFORM CALL_ALV .

ENDFORM .


" [조건] 0.테이블에서 가져오기
DATA : LV_ORDNO_LOW LIKE ZEDT13_100-ZORDNO .
DATA : LV_ORDNO_HIGH TYPE ZEDT13_100-ZORDNO .

FORM GET_DATA .
  LV_ORDNO_LOW = S_ZORDNO-LOW .
  LV_ORDNO_HIGH = S_ZORDNO-HIGH .

  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT         = LV_ORDNO_LOW
    IMPORTING
      OUTPUT        = LV_ORDNO_LOW .
  CALL FUNCTION 'CONVERSION_EXIT_ALPHA_INPUT'
    EXPORTING
      INPUT         = LV_ORDNO_HIGH
    IMPORTING
      OUTPUT        = LV_ORDNO_HIGH .

  RANGES : GR_ORDNO FOR ZEDT13_100-ZORDNO .

  CLEAR GR_ORDNO .
  GR_ORDNO-SIGN = 'I' .
  GR_ORDNO-OPTION = 'BT' .
  GR_ORDNO-LOW = LV_ORDNO_LOW .
  GR_ORDNO-HIGH = LV_ORDNO_HIGH .
  APPEND GR_ORDNO .


  RANGES : GR_JDATE FOR ZEDT13_100-ZJDATE .

  CLEAR GR_JDATE .
  GR_JDATE-SIGN = 'I' .
  GR_JDATE-OPTION = 'BT' .
  GR_JDATE-LOW = S_ZJDATE-LOW .
  GR_JDATE-HIGH = S_ZJDATE-HIGH .
  APPEND GR_JDATE .



  IF P_ZID IS INITIAL AND S_ZMATNR[] IS INITIAL.
    SELECT * FROM ZEDT13_100
    INTO CORRESPONDING FIELDS OF TABLE GT_ORDER
    WHERE ZORDNO IN GR_ORDNO AND ZJDATE IN GR_JDATE .
  ELSEIF P_ZID IS INITIAL AND S_ZMATNR[] IS NOT INITIAL .
    SELECT * FROM ZEDT13_100
    INTO CORRESPONDING FIELDS OF TABLE GT_ORDER
    WHERE ( ZORDNO IN GR_ORDNO ) AND
        ( ZMATNR BETWEEN S_ZMATNR-LOW AND S_ZMATNR-HIGH )
      AND ( ZJDATE IN  GR_JDATE ) .
  ELSEIF P_ZID IS NOT INITIAL AND S_ZMATNR[] IS INITIAL.
    SELECT * FROM ZEDT13_100
    INTO CORRESPONDING FIELDS OF TABLE GT_ORDER
    WHERE ( ZORDNO IN GR_ORDNO ) AND
        ( ZIDCODE EQ P_ZID )
      AND ( ZJDATE IN GR_JDATE ) .
  ELSEIF P_ZID IS NOT INITIAL AND S_ZMATNR[] IS NOT INITIAL.
     SELECT * FROM ZEDT13_100
    INTO CORRESPONDING FIELDS OF TABLE GT_ORDER
    WHERE ( ZORDNO IN GR_ORDNO ) AND
        ( ZIDCODE EQ P_ZID ) AND  ( ZMATNR BETWEEN S_ZMATNR-LOW AND S_ZMATNR-HIGH )
      AND ( ZJDATE IN GR_JDATE ) .
  ENDIF .
*
*  SELECT * FROM ZEDT13_101
*  INTO CORRESPONDING FIELDS OF TABLE GT_DELIVERY .
ENDFORM .


FORM CALL_ALV .

IF GT_ORDER IS NOT INITIAL.
  GT_ORDER_PRINT[] = GT_ORDER[].
ENDIF.

  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      IT_FIELDCAT = GT_FIELDCAT
      I_STRUCTURE_NAME = 'GT_ORDER'
    TABLES
      T_OUTTAB = GT_ORDER_PRINT .
ENDFORM .

FORM FIELD_CATALOG .
  CLEAR : GS_FIELDCAT , GT_FIELDCAT .
  GS_FIELDCAT-COL_POS = 1.
  GS_FIELDCAT-FIELDNAME = 'ZORDNO' .
  GS_FIELDCAT-SELTEXT_M = '주문번호' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .
  CLEAR : GS_FIELDCAT .
  GS_FIELDCAT-COL_POS = 2.
  GS_FIELDCAT-FIELDNAME = 'ZIDCODE' .
  GS_FIELDCAT-SELTEXT_M = '회원ID' .
  APPEND GS_FIELDCAT TO GT_FIELDCAT .

ENDFORM .