*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_BP_TOP
*&---------------------------------------------------------------------*

DATA : OK_CODE TYPE SY-UCOMM .

"필드 카탈로그
DATA : GS_FIELDCAT_PERSON TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT_PERSON TYPE LVC_T_FCAT .
DATA : GS_FIELDCAT_COMPANY TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT_COMPANY TYPE LVC_T_FCAT .
"인터널테이블

"구매처 입력 받는
DATA : BEGIN OF GS_SUPPLIER .
  INCLUDE TYPE ZEDT13_201 .
  INCLUDE TYPE ZEDT13_202 .
DATA : END OF GS_SUPPLIER .

DATA GT_SUPPLIER LIKE TABLE OF GS_SUPPLIER .

DATA : BEGIN OF GS_SUPPLIER_SAVE .
  INCLUDE TYPE ZEDT13_201 .
DATA : END OF GS_SUPPLIER_SAVE .

DATA : GT_SUPPLIER_SAVE LIKE TABLE OF GS_SUPPLIER_SAVE .

DATA : BEGIN OF GS_COUNTRY_CODE_SAVE .
  INCLUDE TYPE ZEDT13_202 .
DATA : END OF GS_COUNTRY_CODE_SAVE .

DATA : GT_COUNTRY_CODE_SAVE LIKE TABLE OF GS_COUNTRY_CODE_SAVE .

"구매조직
DATA : BEGIN OF GS_SUPPLY_ORGANI .
  INCLUDE TYPE ZEDT13_203 .
DATA : END OF GS_SUPPLY_ORGANI .

DATA : GT_SUPPLY_ORGANI LIKE TABLE OF GS_SUPPLY_ORGANI .

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .
DATA : GC_GRID TYPE REF TO CL_GUI_ALV_GRID .



"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .