*&---------------------------------------------------------------------*
*&  Include           ZPROJECT13_PO_SCR
*&---------------------------------------------------------------------*


TABLES : ZEDT13_204, ZEDT13_205 .

SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME .

  "회사코드
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_BUKRS MODIF ID M1 .
  PARAMETERS : P_BUKRS LIKE ZEDT13_204-ZEKKO_BUKRS MODIF ID M1 .
SELECTION-SCREEN END OF LINE.
"구메처
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_LIFNR MODIF ID M1 .
  PARAMETERS : P_LIFNR  LIKE ZEDT13_204-ZEKKO_LIFNR MODIF ID M1 .
SELECTION-SCREEN END OF LINE .
"증빙일
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_BEDAT MODIF ID M1 .
  PARAMETERS : P_BEDAT  LIKE ZEDT13_204-ZEKKO_BEDAT MODIF ID M1 .
SELECTION-SCREEN END OF LINE .

  "구매처코드
SELECTION-SCREEN BEGIN OF LINE.
  SELECTION-SCREEN COMMENT (10) FOR FIELD P_LIFNR2 MODIF ID M2 .
  PARAMETERS : P_LIFNR2 LIKE ZEDT13_204-ZEKKO_LIFNR MODIF ID M2 .
SELECTION-SCREEN END OF LINE.
"회사코드
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_BUKRS2 MODIF ID M2 .
  PARAMETERS : P_BUKRS2  LIKE ZEDT13_204-ZEKKO_BUKRS MODIF ID M2 .
SELECTION-SCREEN END OF LINE .
"PO번호
SELECTION-SCREEN BEGIN OF LINE .
  SELECTION-SCREEN COMMENT (13) FOR FIELD P_EBELN MODIF ID M2 .
  PARAMETERS : P_EBELN  LIKE ZEDT13_204-ZEKKO_EBELN MODIF ID M2 .
SELECTION-SCREEN END OF LINE .

SELECTION-SCREEN END OF BLOCK B1 .

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME .
PARAMETERS : P_CREATE RADIOBUTTON GROUP R1 DEFAULT 'X' USER-COMMAND UC1 .
PARAMETERS : P_LOOKUP RADIOBUTTON GROUP R1 .
SELECTION-SCREEN END OF BLOCK B2 .