*&---------------------------------------------------------------------*
*&  Include           ZEDR13_HW002_TOP
*&---------------------------------------------------------------------*


" [조건] 7. 헤더가 없는 인터널 테이블
* 인터널 테이블 선언 (여러라인 조회하는 용도)
DATA : BEGIN OF GS_ORDER .
  INCLUDE TYPE ZEDT13_100 .
DATA : ZMTART_T TYPE STRING,
      ZSALE_T TYPE STRING,
      ZRET_T TYPE STRING,
      ZCOLOR TYPE C LENGTH 4,
      END OF GS_ORDER.

DATA : GT_ORDER LIKE TABLE OF GS_ORDER .
* [실행조건] 6.인터널 테이블 선언 (출력  용도)
DATA : GT_ORDER_PRINT LIKE GT_ORDER .

"[실행조건9] CONSTANT 사용
CONSTANTS : C_X TYPE CHAR1 VALUE 'X'.

DATA : BEGIN OF GS_DELIVERY .
  INCLUDE TYPE ZEDT13_101 .
DATA : ZCOLOR TYPE C LENGTH 4,
      ZDFLAG_T TYPE STRING,
      ZMTART_T TYPE STRING,
      ZDGUBUN_T TYPE STRING,
      END OF GS_DELIVERY .
DATA : GT_DELIVERY LIKE TABLE OF GS_DELIVERY .

* [실행조건] 6.인터널 테이블 선언 (출력  용도)
DATA : GT_DELIVERY_PRINT LIKE TABLE OF GS_DELIVERY .

"스플리터 2번데이터 학생 마스터 인터널테이블
DATA : BEGIN OF GS_STUDENT .
  INCLUDE TYPE ZEDT13_001 .
DATA : END OF GS_STUDENT .
DATA : GT_STUDENT LIKE TABLE OF GS_STUDENT .
DATA : GT_STUDENT_PRINT LIKE TABLE OF GS_STUDENT .

"스플리터 3번 데이터 자재마스터 인터널테이블
DATA : BEGIN OF GS_MATR .
  INCLUDE TYPE ZEDT13_102 .
DATA : ZWEKRS_T TYPE STRING,
      ZLGORT_T TYPE STRING,
      ZMTARTT_T TYPE STRING ,
      END OF GS_MATR .
DATA : GT_MATR LIKE TABLE OF GS_MATR .
DATA : GT_MATR_PRINT LIKE TABLE OF GS_MATR .


"필드카탈로그
DATA : GS_FIELDCAT TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT TYPE LVC_T_FCAT .

DATA : GS_FIELDCAT2 TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT2 TYPE LVC_T_FCAT .

DATA : GS_FIELDCAT3 TYPE LVC_S_FCAT .
DATA : GT_FIELDCAT3 TYPE LVC_T_FCAT .

"레이아웃
DATA : GS_LAYOUT TYPE LVC_S_LAYO .

" 소계 용 SORT
DATA : GS_SORT TYPE LVC_S_SORT .
DATA : GT_SORT TYPE LVC_T_SORT .

DATA : GS_SORT2 TYPE LVC_S_SORT .
DATA : GT_SORT2 TYPE LVC_T_SORT .

" 스크린 날짜 계산
DATA: LV_YEAR TYPE STRING ,
      LV_JAN_FIRST TYPE D,
      LV_JAN_FMT_STR TYPE STRING,
      LV_JAN_FMT TYPE DATS .

DATA : LV_DATUM_LOW  TYPE SY-DATUM,
  LV_DATUM_HIGH TYPE SY-DATUM.

" DOMAIN FIXED VAL가져오기
DATA: LT_DD07V_MTART TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_SALE_FG TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_RET_FG TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_DGUBUN TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_DFLAG TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_WEKRS TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_LGORT TYPE STANDARD TABLE OF DD07V,
      LT_DD07V_MTARTT TYPE STANDARD TABLE OF DD07V,
      LS_DD07V TYPE DD07V.

" [조건] 0.테이블에서 가져오기
DATA : LV_ORDNO_LOW LIKE ZEDT13_100-ZORDNO .
DATA : LV_ORDNO_HIGH TYPE ZEDT13_100-ZORDNO .

DATA : OK_CODE TYPE SY-UCOMM .

DATA : GC_DOCKING TYPE REF TO CL_GUI_DOCKING_CONTAINER .

DATA : GC_SPLITTER1 TYPE REF TO CL_GUI_SPLITTER_CONTAINER . "첫번째 행 splitter
DATA : GC_SPLITTER2 TYPE REF TO CL_GUI_SPLITTER_CONTAINER . "두번쨰 행 splitter

"0행 0열
DATA : GC_CONTAINER1 TYPE REF TO CL_GUI_CONTAINER .
"0행 1열
DATA : GC_CONTAINER2 TYPE REF TO CL_GUI_CONTAINER .
"1행 0열
"1행 0열
DATA : GC_CONTAINER3 TYPE REF TO CL_GUI_CONTAINER .
"1행 1열
DATA : GC_CONTAINER4 TYPE REF TO CL_GUI_CONTAINER .

"0행
DATA : GC_GRID1 TYPE REF TO CL_GUI_ALV_GRID .
"1행 0열
DATA : GC_GRID2 TYPE REF TO CL_GUI_ALV_GRID .
"1행 1열
DATA : GC_GRID3 TYPE REF TO CL_GUI_ALV_GRID .